services:
  ibmmq:
    image: ibmcom/mq:9.2.4.0-r1  # pin a stable version
    container_name: ibmmq_local
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
